name: Generate badge
on:
  workflow_run:
    workflows: ["Run build"]
    types: [completed]

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - id: extract
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          data=$(gh api /repos/${{ github.repository }}/actions/runs/$RUN_ID/jobs)
          printf "names<<EOF\n%s\nEOF\n"   "$(echo "$data" | jq -r '.jobs[].name')"       >>"$GITHUB_OUTPUT"
          printf "results<<EOF\n%s\nEOF\n" "$(echo "$data" | jq -r '.jobs[].conclusion')" >>"$GITHUB_OUTPUT"

      - uses: DARMA-tasking/badge-generator@1-initial-version
        with:
          names:   ${{ steps.extract.outputs.names }}
          results: ${{ steps.extract.outputs.results }}
          github_token: ${{ secrets.BADGES }}
