name: Test

on:
  pull_request:

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        comment_title: "SA output"
        verbose: true
        exclude_dir: lib
        cmake_args: -DCMAKE_BUILD_TYPE=Debug
        use_cmake: false
        report_pr_changes_only: true
        cppcheck_args: --enable=all --suppress=missingInclude
        clang_tidy_args: -checks='*,fuchsia-*,google-*,zircon-*,abseil-*,modernize-use-trailing-return-type,llvm*,hicpp-uppercase-literal-suffix,readability-uppercase-literal-suffix'
