name: Test (non CMake)

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test the action
      shell: bash
      run: |
          if [ ${GITHUB_EVENT_NAME} = 'push' ]
          then
            echo GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME} using ${GITHUB_REF_NAME}
            BRANCH_NAME=${GITHUB_REF_NAME}
          else
            echo GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME} using ${GITHUB_HEAD_REF}
            BRANCH_NAME=${GITHUB_HEAD_REF}
          fi

          echo BRANCH_NAME=${BRANCH_NAME}

    - name: Run CMake
      shell: bash
      run: |
        cmake -E make_directory ${{runner.workspace}}/build
        cd ${{runner.workspace}}/build
        cmake $GITHUB_WORKSPACE
        cmake --build . 2> >(tee "output.txt")

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@70-support-for-makefile-based-projects
      with:
        verbose: true
        use_cmake: false
        exclude_dir: lib
        cmake_args: -DCMAKE_BUILD_TYPE=Debug
        cppcheck_args: --enable=all --suppress=missingInclude
        clang_tidy_args: -checks='*,fuchsia-*,google-*,zircon-*,abseil-*,modernize-use-trailing-return-type,llvm*,hicpp-uppercase-literal-suffix,readability-uppercase-literal-suffix'
