name: Build on Ubuntu

on: [pull_request]

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: bash
      run: |
        mkdir -p ${{runner.workspace}}/build/some/right
        cd ${{runner.workspace}}/build/some/right
        cmake $GITHUB_WORKSPACE
        cmake --build . 2> >(tee "output.txt")
    - name: Post PR comment for warnings/errors
      if: always()
      uses: JacobDomagala/CompileResult@master
      with:
        comment_title: COMPILE RESULT
        debug_output: true
        compile_result_file: ${{runner.workspace}}/build/output.txt
