name: Static analysis

on:
  push:
    branch:
      - develop
      - master
      - main

  pull_request_target:
    branch:
      - "*"

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout PR tree
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        path: pr_tree

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        verbose: true
        exclude_dir: lib
        cmake_args: -DCMAKE_BUILD_TYPE=Debug
        cppcheck_args: --enable=all --suppress=missingInclude
        clang_tidy_args: -checks='*,fuchsia-*,google-*,zircon-*,abseil-*,modernize-use-trailing-return-type,llvm*,hicpp-uppercase-literal-suffix,readability-uppercase-literal-suffix'
