name: Run build
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [alpine, ubuntu]

    steps:
      - id: docker-build
        run: |
          if [ "${{ matrix.image }}" = "alpine" ]; then
            echo "result=success" >> "$GITHUB_OUTPUT"
          else
            echo "result=failure" >> "$GITHUB_OUTPUT"
          fi

      - name: Record matrix data
        run: |
          echo "${{ matrix.image }}" > target.txt
          echo "${{ steps.docker-build.outputs.result }}" > outcome.txt
      - uses: actions/upload-artifact@v4
        with:
          name: result-${{ matrix.image }}
          path: |
            target.txt
            outcome.txt
