name: Static analysis

on: 
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        verbose: true
