name: Test

on:
  push:
    branches:
      - develop
      - master
      - main

  pull_request_target:
    branches:
      - "*"

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test the action
      shell: bash
      run: |
          if [ ${GITHUB_EVENT_NAME} = 'push' ]
          then
            echo GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME} using ${GITHUB_REF_NAME}
            BRANCH_NAME=${GITHUB_REF_NAME}
          else
            echo GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME} using ${GITHUB_HEAD_REF}
            BRANCH_NAME=${GITHUB_HEAD_REF}
          fi

          echo BRANCH_NAME=${BRANCH_NAME}

    - name: Run CMake
      shell: bash
      run: |
        cmake -E make_directory ${{runner.workspace}}/build
        cd ${{runner.workspace}}/build
        cmake $GITHUB_WORKSPACE
        cmake --build . 2> >(tee "output.txt")

    - name: Post PR comment for warnings/errors
      if: ${{ always() }} && github.ref != 'refs/heads/master'
      uses: JacobDomagala/CompileResultAction@master
      with:
        comment_title: UBUNTU COMPILE RESULT
        compile_result_file: ${{runner.workspace}}/build/output.txt

    - name: Run static analysis (CMake)
      if: ${{ always() }}
      uses: JacobDomagala/StaticAnalysis@master
      with:
        comment_title: "SA CMake output"
        verbose: true
        exclude_dir: lib
        cmake_args: -DCMAKE_BUILD_TYPE=Debug
        cppcheck_args: --enable=all --suppress=missingInclude
        clang_tidy_args: -checks='*,fuchsia-*,google-*,zircon-*,abseil-*,modernize-use-trailing-return-type,llvm*,hicpp-uppercase-literal-suffix,readability-uppercase-literal-suffix'

    - name: Run static analysis (non CMake)
      if: ${{ always() }}
      uses: JacobDomagala/StaticAnalysis@master
      with:
        comment_title: "SA non-CMake output"
        verbose: true
        use_cmake: false
        exclude_dir: lib
        cmake_args: -DCMAKE_BUILD_TYPE=Debug
        cppcheck_args: --enable=all --suppress=missingInclude
        clang_tidy_args: -checks='*,fuchsia-*,google-*,zircon-*,abseil-*,modernize-use-trailing-return-type,llvm*,hicpp-uppercase-literal-suffix,readability-uppercase-literal-suffix'