name: Run build
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: build-${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [alpine, ubuntu]

    steps:
      - id: docker-build
        run: |
          if [ "${{ matrix.image }}" = "alpine" ]; then
            echo "result=success" >>"$GITHUB_OUTPUT"
          else
            echo "result=failure" >>"$GITHUB_OUTPUT"
          fi
