name: Build on Multiple OS

on: [pull_request]

jobs:
  Compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Create Working Directory
      run: mkdir -p ${{runner.workspace}}/build

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        cmake $GITHUB_WORKSPACE
        cmake --build . 2> >(tee "output.txt")

    - name: Post PR comment for warnings/errors
      if: always()
      uses: JacobDomagala/CompileResult@31-warnings-with-relative-paths-not-parsed
      with:
        comment_title: COMPILE RESULT (${{ matrix.os }})
        debug_output: true
        compile_result_file: ${{runner.workspace}}/build/output.txt
